### ISSUE TITLE
Masked GCN

### ISSUE THREAD

**Issue by cjissmart** [marble0117/GNN_models_pytorch#1]
Whether you notice that Masked-GCN model in the paper only has a weight matrix following H(2) (node features) ? In your implementation, node features are calculated by a GCN layer after node features multiply with the mask vector. It is confusing that the reproduction's accuracy  of the paper in Cora (about 76%) is worse than your implementation (about 80.7%). However, the accuracy of Cora is 82.7% (sym type).

**Comment by marblet** [comment]
I understand my implementation of Masked-GCN is obviously wrong.... Thank you for pointing out it! I will fix and republish it.
Thank you.

**Comment by cjissmart** [comment]
> I understand my implementation of Masked-GCN is obviously wrong.... Thank you for pointing out it! I will fix and republish it.
> Thank you.

Yeah. If possible, you can try to compare the current Masked GCN code with the code you modify. The accuracy may significantly drop.

**Comment by YongZh131** [comment]
> Whether you notice that Masked-GCN model in the paper only has a weight matrix following H(2) (node features) ? In your implementation, node features are calculated by a GCN layer after node features multiply with the mask vector. It is confusing that the reproduction's accuracy of the paper in Cora (about 76%) is worse than your implementation (about 80.7%). However, the accuracy of Cora is 82.7% (sym type).

Is your code shared by the author or implemented by yourself?

**Comment by YongZh131** [comment]
> Whether you notice that Masked-GCN model in the paper only has a weight matrix following H(2) (node features) ? In your implementation, node features are calculated by a GCN layer after node features multiply with the mask vector. It is confusing that the reproduction's accuracy of the paper in Cora (about 76%) is worse than your implementation (about 80.7%). However, the accuracy of Cora is 82.7% (sym type).

Is your code shared by the author or implemented by yourself? I tried to modify the blogger's code to match the paper. As a result, the test_acc of the first run was 0.75, the second run was 0.78, and the running time was longer.

**Comment by marblet** [comment]
My codes is not shared by the author and contains some mistakes.
Please do not use the implementation of Masked GCN for your experiments.
Now I am trying to implement it correctly and reproduce the score in the paper.
I apologize for the inconvenience.
